### ISSUE TITLE
请问标题首字母自动大写怎么修改？

### ISSUE THREAD

**Issue by petcat** [Y4er/hugo-theme-easybook#4]
现在的情况是，标题有字母单词的话，首字母自动大写，无法控制，想知道在哪可以修改。

模板会修改，这个就不会了，不知是哪个Css , Js 的 （嗯，现在标题是会这样表现）

**Comment by Y4er** [comment]
https://github.com/Y4er/hugo-theme-easybook/blob/48555b80234918a743a1cc52f3868fb37cb055f3/layouts/index.html#L12

去掉title函数即可
![image](https://user-images.githubusercontent.com/40487319/80047147-3b25fa80-853f-11ea-9cd9-09306ce3a62f.png)

参考 https://gohugo.io/functions/title/

**Comment by petcat** [comment]
非常感谢。

原来还是模板啊，还以为是某个 css js 控制的，因为第一次遇到这样的自动首字母大写的，再次感谢。
