### ISSUE TITLE
无法正常显示来自畅言云评的评论

### ISSUE THREAD

**Issue by LiuShaoYeCC** [Y4er/hugo-theme-easybook#5]
现在畅言云评V3版本大改，导致无法正常更改
![image](https://user-images.githubusercontent.com/58081491/116836505-55d28b00-abf9-11eb-8ab4-ac6f538a2653.png)

**Comment by Y4er** [comment]
建议使用别的评论系统，或者修改 https://github.com/Y4er/hugo-theme-easybook/blob/master/layouts/partials/comments.html 文件的内容来进行适配。欢迎pr
